# Generated by Django 2.2.16 on 2023-08-10 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20230808_1858'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingCard',
        ),
    ]
